
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: './manifest.json'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="link-wrapper">
            <Link href="/">Home</Link>
          </div>
          <div className="link-wrapper">
            <Link href="/instruction">Instructions</Link>
          </div>
          <div className="link-wrapper">
            <Link href="main">Main</Link>
          </div>
        </nav>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
